#!/bin/sh
cd /systemf
/usr/bin/systemf-build

export SHOULD_NOT_FORK=true
export SHOULD_NOT_CAPTURE_STDOUT_STDERR=true

GDBSERVER_TARGET=${GDBSERVER_TARGET:-python3 tests/test.test}
GDBSERVER_PORT=${GDBSERVER_PORT:-2345}

gdbserver :$GDBSERVER_PORT $GDBSERVER_TARGET
